% Copyright 2013 Barzan Mozafari
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
%     http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.

function createaxes(Parent1, X1, YMatrix1, X2, Y1, X3, X4, YMatrix2)
%CREATEAXES(PARENT1,X1,YMATRIX1,X2,Y1,X3,X4,YMATRIX2)
%  PARENT1:  axes parent
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  Y1:  vector of y data
%  X3:  vector of x data
%  X4:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 29-Jan-2012 16:49:14

% Create axes
axes1 = axes('Parent',Parent1,...
    'Position',[0.109375 0.182885906040268 0.875 0.76510067114094],...
    'FontSize',40);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[400 850]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',6.5);
set(plot1(1),'Marker','o','LineStyle','none','Color',[0 0 1],...
    'DisplayName','Actual (Wiki100K)');
set(plot1(2),'Color',[1 0 1],'DisplayName','Predicted (Wiki100K)');

% Create plot
plot(X2,Y1,'Parent',axes1,'DisplayName','Actual (Wiki1K)','Color',[0 0 0]);

% Create plot
plot(X3,Y1,'Parent',axes1,'Color',[0 1 1],...
    'DisplayName','Predicted (Wiki1K)');

% Create xlabel
xlabel('TPS','FontSize',40);

% Create ylabel
ylabel(['',sprintf('\n'),'CPU (%)'],'FontSize',40);

% Create multiple lines using matrix input to plot
plot2 = plot(X4,YMatrix2,'Parent',axes1);
set(plot2(1),'MarkerSize',18,'Marker','o','LineWidth',2,'LineStyle','Actual (Wiki1K)',...
    'Color',[0 1 0]);
set(plot2(2),'LineWidth',4,'LineStyle',':','Color',[0 0 0]);

